openapi: 3.0.3
info:
  title: foo-bar
  description: foo-bar
  version: 1.0.0
  contact:
    name: hnsfy
servers:
  - url: http://localhost:5000
    description: local
paths:
  /:
    get:
      summary: test
      operationId: test
      description: 生成一个序列号。如果传入了err参数，抛出错误
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seq"
      tags:
        - FooBar
      parameters:
        - schema:
            type: string
          in: query
          name: err
    parameters: []
components:
  schemas:
    Seq:
      title: Seq
      type: object
      description: "test返回报文（序列号） "
      properties:
        value:
          type: integer
          format: int64
        create_time:
          type: string
          description: 创建时间
          format: date-time
      required:
        - value
        - create_time
  securitySchemes:
    apiKey1:
      name: X-API-KEY
      type: apiKey
      in: header
tags:
  - name: FooBar
security:
  - apiKey1: []
